spring.application.name=payment_processing

spring.datasource.url=jdbc:mysql://localhost:3306/payment_processing
spring.datasource.username=root
spring.datasource.password=n3u3da!


# Step 02: execute schema.sql and data.sql even for an external MySQL database.
spring.sql.init.mode=always

# Stop startup when the schema or seed script contains an error.
spring.sql.init.continue-on-error=false

# Read SQL files as UTF-8.
spring.sql.init.encoding=UTF-8

# Payment Scheduler ? interval in milliseconds (default: 60 000 = 1 minute)
scheduler.payment.fixed-delay-ms=60000

