spring.application.name=payment_processing

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/payment_processing}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:n3u3da!}

spring.sql.init.mode=always

# Stop startup when the schema or seed script contains an error.
spring.sql.init.continue-on-error=false

# Read SQL files as UTF-8.
spring.sql.init.encoding=UTF-8

# Payment Scheduler ? interval in milliseconds (default: 60 000 = 1 minute)
scheduler.payment.fixed-delay-ms=60000

