package com.devsquad.payment_processing.model;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.sql.Date;
import java.sql.Time;

public class Payment {

    public Payment() {

    }

    public enum Status {
        CREATED,      // Initial status when payment is created
        VALIDATING,   // Validating account balance and details
        COMPLETED,    // Payment successfully completed
        FAILED,       // Payment failed
        CANCELLED     // Payment cancelled by user
    }

    // Auto-generated by database
    private Integer paymentId;
    
    // Auto-generated if not provided (format: INV-{timestamp})
    private String invoiceNumber;
    
    @NotNull(message = "Sender account number is required")
    private Long senderAccountNumber;
    
    @NotNull(message = "Receiver account number is required")
    private Long receiverAccountNumber;
    
    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be positive")
    private Double amount;
    
    // Optional - if null, uses default currency
    private Integer currencyId;
    
    @NotNull(message = "Payment mode ID is required")
    private Integer paymentModeId;
    
    // Auto-set to current date/time if not provided
    private Date paymentDate;
    private Time paymentTime;
    
    // Optional
    private String description;
    
    // Optional - only set when payment is executed from a schedule
    private Integer scheduleId;
    
    // Auto-set to PENDING if not provided
    private Status status;

    public Payment(Integer paymentId, String invoiceNumber, Long senderAccountNumber, Long receiverAccountNumber,
                   Double amount, Integer currencyId, Integer paymentModeId, Date paymentDate, Time paymentTime,
                   String description, Integer scheduleId, Status status) {
        this.paymentId = paymentId;
        this.invoiceNumber = invoiceNumber;
        this.senderAccountNumber = senderAccountNumber;
        this.receiverAccountNumber = receiverAccountNumber;
        this.amount = amount;
        this.currencyId = currencyId;
        this.paymentModeId = paymentModeId;
        this.paymentDate = paymentDate;
        this.paymentTime = paymentTime;
        this.description = description;
        this.scheduleId = scheduleId;
        this.status = status;
    }

    public Integer getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public Long getSenderAccountNumber() {
        return senderAccountNumber;
    }

    public void setSenderAccountNumber(Long senderAccountNumber) {
        this.senderAccountNumber = senderAccountNumber;
    }

    public Long getReceiverAccountNumber() {
        return receiverAccountNumber;
    }

    public void setReceiverAccountNumber(Long receiverAccountNumber) {
        this.receiverAccountNumber = receiverAccountNumber;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Integer getCurrencyId() {
        return currencyId;
    }

    public void setCurrencyId(Integer currencyId) {
        this.currencyId = currencyId;
    }

    public Integer getPaymentModeId() {
        return paymentModeId;
    }

    public void setPaymentModeId(Integer paymentModeId) {
        this.paymentModeId = paymentModeId;
    }

    public Date getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public Time getPaymentTime() {
        return paymentTime;
    }

    public void setPaymentTime(Time paymentTime) {
        this.paymentTime = paymentTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getScheduleId() {
        return scheduleId;
    }

    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

}
